/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutCityPageImport } from './routes/_layout/city-page'
import { Route as LayoutCityDetailImport } from './routes/_layout/city-detail'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCityPageRoute = LayoutCityPageImport.update({
  path: '/city-page',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCityDetailRoute = LayoutCityDetailImport.update({
  path: '/city-detail',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/city-detail': {
      preLoaderRoute: typeof LayoutCityDetailImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/city-page': {
      preLoaderRoute: typeof LayoutCityPageImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutCityDetailRoute,
    LayoutCityPageRoute,
    LayoutItemsRoute,
    LayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
